---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kerberos-config
  namespace: default
data:
  krb5.conf: |
    [libdefaults]
        default_realm = YOUR.DOMAIN.COM
        dns_lookup_realm = false
        dns_lookup_kdc = true
        ticket_lifetime = 24h
        renew_lifetime = 7d
        forwardable = true
        rdns = false
        default_ccache_name = FILE:/tmp/krb5cc_%{uid}

    [realms]
        YOUR.DOMAIN.COM = {
            kdc = kdc.your.domain.com
            admin_server = kdc.your.domain.com
        }

    [domain_realm]
        .your.domain.com = YOUR.DOMAIN.COM
        your.domain.com = YOUR.DOMAIN.COM

    [logging]
        default = STDERR

---
# Create this secret with:
# kubectl create secret generic kerberos-keytab \
#   --from-file=krb5.keytab=/path/to/your/krb5.keytab
apiVersion: v1
kind: Secret
metadata:
  name: kerberos-keytab
  namespace: default
type: Opaque
# data:
#   krb5.keytab: <base64-encoded-keytab>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mssql-app
  template:
    metadata:
      labels:
        app: mssql-app
    spec:
      containers:
      - name: app
        image: mssql-app:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        # Application configuration
        - name: PORT
          value: "8080"
        - name: MSSQL_SERVER
          value: "yourserver.database.windows.net"
        - name: MSSQL_DATABASE
          value: "yourdatabase"
        
        # Kerberos configuration
        - name: KRB5_CONFIG
          value: /etc/kerberos/krb5.conf
        - name: KRB5_KTNAME
          value: /etc/kerberos/krb5.keytab
        - name: KRB5CCNAME
          value: /tmp/krb5cc_app
        - name: KRB5_PRINCIPAL
          value: "yourapp@YOUR.DOMAIN.COM"
        
        volumeMounts:
        - name: kerberos-config
          mountPath: /etc/kerberos/krb5.conf
          subPath: krb5.conf
          readOnly: true
        - name: kerberos-keytab
          mountPath: /etc/kerberos/krb5.keytab
          subPath: krb5.keytab
          readOnly: true
        - name: krb-cache
          mountPath: /tmp
        
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      
      volumes:
      - name: kerberos-config
        configMap:
          name: kerberos-config
      - name: kerberos-keytab
        secret:
          secretName: kerberos-keytab
          defaultMode: 0600
      - name: krb-cache
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mssql-app
  namespace: default
spec:
  selector:
    app: mssql-app
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
